artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_query: SELECT * FROM ClothesDB.clothingsSales
  load_data: artifacts/data_ingestion/clothesDataset.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  clothSalesDataset: artifacts/data_ingestion/clothesDataset.csv
  load_data: artifacts/data_preprocessing/cleanDataset.csv
  preprocessModel: artifacts/data_preprocessing/preprocess.joblib

data_validation:
  root_dir: artifacts/data_validation
  cleanDataset: artifacts/data_preprocessing/cleanDataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_splitting:
  root_dir: artifacts/data_splitting
  cleanData: artifacts/data_preprocessing/cleanDataset.csv
  trainData: artifacts/data_splitting/train.csv
  testData: artifacts/data_splitting/test.csv
  